os:
- linux
language: go
sudo: required
go:
- 1.13.x
dist: bionic
addons:
  sonarcloud:
    organization: paysuper
stages:
- test
- name: deploy
  if: branch IN (develop, feature/190525, casbin_middleware)
- name: deploy-stg-rb
  if: branch =~ ^release
- name: deploy-stg-tag
  if: tag =~ ^v    

env:
  global:
  - GO111MODULE=on
  - AWS_ACCESS_KEY_ID_AGREEMENT=key_id
  - AWS_SECRET_ACCESS_KEY_AGREEMENT=secret_key
  - AWS_REGION_AGREEMENT=eu-west-1
  - AWS_BUCKET_AGREEMENT=bucket
  - ORDER_INLINE_FORM_URL_MASK=https://paysupermgmt.tst.protocol.one/order
  - AWS_CLOUDWATCH_ACCESS_KEY_ID=aws_cloudwatch_access_key_id
  - AWS_CLOUDWATCH_SECRET_ACCESS_KEY=aws_cloudwatch_secret_access_key
  - AWS_CLOUDWATCH_LOG_GROUP_BILLING_SERVER=aws_cloudwatch_log_group_billing_server
  - AWS_CLOUDWATCH_LOG_GROUP_MANAGEMENT_API=aws_cloudwatch_log_group_management_api
  - AWS_CLOUDWATCH_LOG_GROUP_WEBHOOK_NOTIFIER=aws_cloudwatch_log_group_webhook_notifier
  - AWS_ACCESS_KEY_ID_MERCHANTDOCS=key_id
  - AWS_SECRET_ACCESS_KEY_MERCHANTDOCS=secret_key
  - AWS_REGION_MERCHANTDOCS=eu-west-1
  - AWS_BUCKET_MERCHANTDOCS=bucket
jobs:
  include:
  - stage: test
    cache:
      directories:
      - $HOME/gopath/pkg/mod
#    before_install:
#    - wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
#    - tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
#    - sudo mv wkhtmltox/bin/wkhtmltopdf /usr/local/bin      
    install: true
    script:
    #- go test ./... -coverprofile=coverage.out -covermode=atomic -p=1
    - make github-test
    - sonar-scanner
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger
  - stage: deploy-stg-rb
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH -e DEPLOY_TO_ENV="stg" -e IS_RB="true"
      p1hub/p1jenkinstrigger
  - stage: deploy-stg-tag
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_TAG -e DEPLOY_TO_ENV="stg"
      p1hub/p1jenkinstrigger      
notifications:
  email: false
  slack:
    secure: TNjvJwLocb9aJHFv+KECW/09dTTqRl4jE2p+MKDnr2uf+CqfDAjsanx2eEPjw9rUeSPfJUQ1ZUVTyv+nQKslMippgCpz9Wo9+PPw/gaNoY5niVpNPRE2TmjKyZoDx8xYYfXi+gwUWWOz6hHCv6Vb1edBmDvsoXXSuNuUxYLsUjN9mDFDutrFNC29K9iDfTHr9yBgVmjffOdph0dtybpr6aunBXnvVhBIX/XNNf697Yu6DkJAOfSPcCbREXmR/J5BGwNAgEA/jBH5XjLdYFyuJGHuDAAgOv0OPPC6Laly4cb+6yb7cqjD8iN1RnQm5k1hFBFYZA7lWjy9bHcf24pzGg2dHSvSEuFGpvV6EKx2wv7rWSPpQM5tug0nDTGJJAU23iKWsXK7cmjb11m3acrKyUj84ckmmBrRD9urUGOISphOYynclg2em7jRh64lf4aLoO8ErFm2VlD+KCN1qTBblIHPm6h2aUaT0WPlekYXssh177xfroLuO6QZIwj+4ipP9/but2vqA0jXyzk2jAl4fUrowDH0+VbWxpaYE0YYbt8VgyZpn/TbJv3C0Ni58/txOeKcUmoYOiZuJqOPWiIWpjixCrtru8lvck28EyIH3IQCqN5WZ8beBkC2HQKsZu+ktTATRYrghprqGmaAqbWr17JZ6mob/rXvNE4+PtPNow4=
git:
  submodules: false
